blank_issues_enabled: true
contact_links:
  - name: GSD Tools
    url: https://github.com/cloudsecurityalliance/gsd-tools/issues/new
    about: For issues related to GSD tooling, please create an issue in the GSD Tools Repo.
  - name: GSD Project
    url: https://github.com/cloudsecurityalliance/gsd-project/issues/new
    about: For issues that aren't related to the tooling or GSD entries, please use the GSD Project Repo to create an issue.
