name: GSD ID Request
description: Request a new GSD ID.
title: "[REQUEST]: "
body:
  - type: markdown
    attributes:
      value: |
        To create a new GSD, please fill out the following fields.
